### ISSUE TITLE
Error Cannot read properties of undefined version.startsWith

### ISSUE THREAD

**Issue by fairking** [Manweill/swagger-axios-codegen#163]
I have got the following error when I run codegen against a very simple schema:
```
openApi version： undefined
C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\utils.js:260
    return version.startsWith('3.', 0);
                   ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at isOpenApi3 (C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\utils.js:260:20)
    at C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\index.js:104:45
    at Generator.next (<anonymous>)
    at C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\index.js:23:12)
    at codegen (C:\Code\MyProject\node_modules\swagger-axios-codegen\dist\index.js:68:12)
    at Object.<anonymous> (C:\Code\MyProject\codegen.js:4:1)
```

swagger settings:
``` js
const { codegen } = require("swagger-axios-codegen");

// See docs: https://www.npmjs.com/package/swagger-axios-codegen
codegen({
  serviceNameSuffix: "",
  enumNamePrefix: "",
  methodNameMode: "operationId", // "[operationId|path]"
  source: "../MyProject.Domain/schema.json",
  outputDir: "./src/services",
  fileName: "core.ts",
  strictNullChecks: false,
  useStaticMethod: true,
  useCustomerRequestInstance: false,
  /* List of api services which need to be generated in TS. */
  include: [
    "StoreService",
  ],
  /* Additional types/enums not included in the api methods. Those types must have attribute [ApiModel] */
  includeTypes: [
    "IdForm",
  ],
  modelMode: "class",
  extendGenericType: [],
  generateValidationModel: true,
});
```

schema.json:
``` json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Open API Napos Scheme",
    "version": "1.0.0"
  },
  "paths": {
    "Store": {
      "post": {
        "operationId": "GetList",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/StoreItem"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateStoreForm": {
        "required": [
          "Name"
        ],
        "type": "object",
        "properties": {
          "Name": {
            "maxLength": 50,
            "type": "string",
            "nullable": true
          },
          "Description": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "StoreForm": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string",
            "nullable": true
          },
          "Name": {
            "type": "string",
            "nullable": true
          },
          "Description": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "IdForm": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "StoreItem": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "string",
            "nullable": true
          },
          "Created": {
            "type": "string",
            "format": "date-time"
          },
          "Updated": {
            "type": "string",
            "format": "date-time"
          },
          "Name": {
            "type": "string",
            "nullable": true
          },
          "Description": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by fairking** [comment]
ok, in my case it was my mistake:
instead of this:
``` json
source: '../MyProject.Domain/schema.json',
```
it needs to be this:
``` json
source: require('../MyProject.Domain/schema.json'),
```

**Comment by UnicornXU** [comment]
仍未解决
const { codegen } = require('swagger-axios-codegen')
const root = 'http://whaleapi.internal.zhcxkj.com/'
codegen({
    methodNameMode: 'operationId',
    remoteUrl: root + '/profit/v2/api-docs',
    outputDir: './src/api/profit'
});
