### ISSUE TITLE
Need normalize class name and perhaps other names

### ISSUE THREAD

**Issue by zaaack** [Manweill/swagger-axios-codegen#17]
error { SyntaxError: '{' expected. (2376:17)
  2374 |   
  2375 | 
> 2376 |   export class x-any {
       |                 ^
  2377 | 
  2378 |     
  2379 | 
    at e (/Users/z/Projects/Node/turtle/node_modules/prettier/parser-typescript.js:1:267)
    at Object.parse (/Users/z/Projects/Node/turtle/node_modules/prettier/parser-typescript.js:1:2172547)
    at Object.parse$2 [as parse] (/Users/z/Projects/Node/turtle/node_modules/prettier/index.js:10639:19)
    at coreFormat (/Users/z/Projects/Node/turtle/node_modules/prettier/index.js:13856:23)
    at format (/Users/z/Projects/Node/turtle/node_modules/prettier/index.js:14115:73)
    at formatWithCursor (/Users/z/Projects/Node/turtle/node_modules/prettier/index.js:14131:12)
    at /Users/z/Projects/Node/turtle/node_modules/prettier/index.js:42399:15
    at Object.format (/Users/z/Projects/Node/turtle/node_modules/prettier/index.js:42418:12)
    at format (/Users/z/Projects/Node/turtle/node_modules/swagger-axios-codegen/dist/index.js:188:31)
    at codegen (/Users/z/Projects/Node/turtle/node_modules/swagger-axios-codegen/dist/index.js:162:72)
  loc: { start: { line: 2376, column: 17 } },
  codeFrame:
   '\u001b[0m \u001b[90m 2374 | \u001b[39m  \u001b[0m\n\u001b[0m \u001b[90m 2375 | \u001b[39m\u001b[0m\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 2376 | \u001b[39m  \u001b[36mexport\u001b[39m \u001b[36mclass\u001b[39m x\u001b[33m-\u001b[39many {\u001b[0m\n\u001b[0m \u001b[90m      | \u001b[39m                \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2377 | \u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2378 | \u001b[39m    \u001b[0m\n\u001b[0m \u001b[90m 2379 | \u001b[39m\u001b[0m' }
finish: 692.269ms
✨  Done in 4.44s.

**Comment by Manweill** [comment]
The master branch is fix this issue

**Comment by Manweill** [comment]
@zaaack v0.5.2 was published
