### ISSUE TITLE
can't support openapi3.0

### ISSUE THREAD

**Issue by heavenkiller2018** [Manweill/swagger-axios-codegen#21]
when i use  a json file with openapi3.0, like:

{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Swagger Petstore",
    "description" : "This is a sample Petstore server.  You can find\nout more about Swagger at\n[http://swagger.io](http://swagger.io) or on\n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n",
    "termsOfService" : "http://swagger.io/terms/",
    "contact" : {
      "email" : "apiteam@swagger.io"
    },
...

the following error occured:
error TypeError: Cannot read property 'slice' of undefined
    at Object.refClassName (D:\**\swagger-axios-codegen\example\node_modules\swagger-axios-codegen\dist\utils.js:24:22)
    at params.forEach.p (D:\**\swagger-axios-codegen\dist\requestCodegen\getRequestParameters.js:21:36)
    at Array.forEach (<anonymous>)
    at Object.getRequestParameters (D:\**\example\node_modules\swagger-axios-codegen\dist\requestCodegen\getRequestParameters.js:16:12)
    at Object.requestCodegen (D:\**\example\node_modules\swagger-axios-codegen\dist\requestCodegen\index.js:28:59)
    at codegen (D:\**\example\node_modules\swagger-axios-codegen\dist\index.js:140:45)
    at Object.<anonymous> (D:\**\example\swagger\codegen.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by Manweill** [comment]
@heavenkiller2018 
emmm, it dose not support swagger3.0 now.
