### ISSUE TITLE
With JIRA API it shows an error

### ISSUE THREAD

**Issue by jkulcsar** [Manweill/swagger-axios-codegen#63]
Trying to generate a client from the JIRA API at:
https://developer.atlassian.com/cloud/jira/platform/swagger.v3.json

shows the error:
```
openApi version： 3.0.1
isV3 true
(node:25456) UnhandledPromiseRejectionWarning: Error: Could not find property type on schema
    at Object.getRequestBody (C:\Users\kulcsar\source\repos\demo\node_modules\swagger-axios-codegen\dist\requestCodegen\getRequestBody.js:29:19)
    at Object.requestCodegen (C:\Users\kulcsar\source\repos\demo\node_modules\swagger-axios-codegen\dist\requestCodegen\index.js:46:54)
    at C:\source\repos\demo\node_modules\swagger-axios-codegen\dist\index.js:74:62
```

Any ideas what could cause this?
Any help is much appreciated, this is a great codegen and I'm using it successfully on other APIs but been stuck on the JIRA API.

Many thanks!

**Comment by jkulcsar** [comment]
Many thanks again, works great!
