### ISSUE TITLE
TypeError: types is not iterable

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [Manweill/swagger-axios-codegen#67]
After upgrading from 0.9.7 to 0.9.9 got the following error:
npm: '6.13.6',
node: '12.14.1',
```
(node:26524) UnhandledPromiseRejectionWarning: TypeError: types is not iterable
    at Object.setDefinedGenericTypes (C:\Code\swagger-axios-codegen\dist\utils.js:11:79)
    at C:\Code\swagger-axios-codegen\dist\index.js:52:17
    at Generator.next (<anonymous>)
    at C:\Code\swagger-axios-codegen\dist\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Code\swagger-axios-codegen\dist\index.js:4:12)
    at codegen (C:\Code\swagger-axios-codegen\dist\index.js:48:12)
    at Object.<anonymous> (C:\Code\Maximus\src\Maximus.App\codegen.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

My codegen.js looks like this:
```
const { codegen } = require("swagger-axios-codegen");

codegen({
	serviceNameSuffix: "Service",
	enumNamePrefix: "Enum",
	methodNameMode: "operationId",
	remoteUrl: "http://localhost:8050/api/v1/swagger.json",
	outputDir: "./src/services",
	strictNullChecks: false,
	useStaticMethod: true,
	useCustomerRequestInstance: false,
	include: [],
	modelMode: "class"
});
```

**Comment by denis-pujdak-adm-it** [comment]
Looks like clean npm install helped to get rid of the error.
